pilsbot_indiator_bridge:
  ros__parameters:
    serial_port: "/dev/ttyLighting"
    baud_rate: 115200

pilsbot_stvo_translation:
  ros__parameters:
    ackermann_topic_from: "pilsbot_velocity_controller/cmd_vel"
    light_teleop_prefix: "cmd/"
    prefix_lighting_publish: ""
    turning_threshold_rad: .31415
    tagfahrlicht: True
    tagfahrlicht_intensity: 0x60
    brakelight_diff_m_s: 0.04  # turn on brake light if new command is x slower
    min_brake_time_s: .5
    hazard_when_backing_up: True
    backwards_hazard_m_s: .1
